---
- name: Provision a new server with hardened SSH and basic iptables.

  # Specify the hosts you want to target
  hosts: nodes

  # Specify the user you want to connect to the server.
  # With a new installation, you will connect with `root`. If you want to
  # re-run this playbook at a later date, you should change `remote_user` to
  # the user you specified under `vars/username` below and uncomment the
  # `become: true` line. You should then run the playbook using the
  # `--ask-become-pass` flag.
  remote_user: root
  #become: true

  vars:
    username: devuser

    # Check the README for information about creating a hashed password
    password: $6$rounds=656000$L40GiyDPuxE1f/kS$fswrMKHVZz3yiruJGoY2BPYHy3viKVIH5Mkb8.AUo8K8eAL7VMoagXVCu7pgn4f3GMYAbra3sAN.hKqr7MANc/
    public_key: ~/.ssh/id_rsa.pub

  roles:
    - user
    - packages
    - ssh
    - iptables
    - fail2ban
    - reboot
