---

- name: Upgrading all packages (Ubuntu/Debian)
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Upgrading all packages (CentOS)
  yum:
    name: '*'
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Install a few more packages
  package:
    name: "{{item}}"
    state: present
  with_items:
   - git
   - vim
   - htop
   - lynis
   - screen
   - ranger
   - mercurial

- name: Install a few more packages for lynis
  package:
    name: "{{item}}"
    state: present
  with_items:
   - debian-goodies
   - apt-listchanges
   - debsecan
   - debsums
  when: ansible_os_family == "Debian"

- name: Install apt-listbugs from debian mirror
  apt:
    deb: http://ftp.us.debian.org/debian/pool/main/a/apt-listbugs/apt-listbugs_0.1.24_all.deb
  when: ansible_os_family == "Debian"

- name: Install the `unattended-upgrades` package
  package:
    name: unattended-upgrades
    state: present
  when: ansible_os_family == "Debian"

- name: Copy the `20auto-upgrades` configuration file
  copy:
    src: ../templates/20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Debian"
